import type { Project } from "./types";

export const PROJECTS: Project[] = [
  /* ...tous les objets du tableau que je t’ai donné... */

   {
    title: "GStock (Django) — Stock & Orders",
    category: "Web Apps",
    description:
      "Django app for products, orders, and stock with admin auth and responsive Bootstrap UI.",
    image: "/images/projets/gstock-django.jpg",
    icon: "🧱",
    tags: ["Python", "Django 2.2+", "SQLite", "Bootstrap 4"],
    features: [
      "Secure auth (Admin)",
      "Products & Categories CRUD",
      "Orders: draft → validated → delivered",
      "Auto stock decrement + low-stock checks",
      "Responsive templates",
    ],
    link: "https://github.com/AnasKrir/G_Stock",
  },
  {
    title: "KY-CHAT — Real-Time Rooms",
    category: "Web Apps",
    description:
      "Simple real-time chat rooms with Django, classic templates & AJAX for instant messages.",
    image: "/images/projets/kychat.jpg",
    icon: "💬",
    tags: ["Django", "SQLite", "HTML/CSS/JS", "AJAX"],
    features: [
      "Create/Join chat rooms",
      "Django auth",
      "Instant messages (AJAX)",
      "Extendable to WebSockets",
    ],
    link: "https://github.com/AnasKrir/KY-CHAT",
  },
  {
    title: "Dentopro — Dental Clinic (Swing)",
    category: "Desktop Apps",
    description:
      "Java desktop app (Swing) to manage patients, appointments, invoices and medical files.",
    image: "/images/projets/dentopro.jpg",
    icon: "🦷",
    tags: ["Java 23", "Swing", "MVC", "Maven", "Lombok"],
    features: [
      "Patients, appointments, invoices",
      "Roles (Dentist/Secretary)",
      "TXT file storage (no DB)",
      "Ready-to-run desktop app",
    ],
    link: "https://github.com/AnasKrir/DENTOPRO",
  },
  {
    title: "Bankati Web App — Banking",
    category: "Web Apps",
    description:
      "Spring Boot banking app with users, accounts, credits, roles and secure authentication.",
    image: "/images/projets/bankati.jpg",
    icon: "🏦",
    tags: ["Java 17", "Spring Boot 3.5", "JPA/Hibernate", "MySQL", "Thymeleaf", "Security"],
    features: [
      "Admin/Client auth & roles",
      "Accounts & credits management",
      "Credit history",
      "Responsive UI (Thymeleaf + CSS)",
    ],
    link: "https://github.com/AnasKrir/BANKATI",
  },
  {
    title: "HotelManagement — .NET MVC",
    category: "Web Apps",
    description:
      "Hotel management (rooms, bookings, clients, payments) with Razor + SQL Server.",
    image: "/images/projets/hotel.jpg",
    icon: "🏨",
    tags: [".NET 8 MVC", "C#", "SQL Server", "EF Core", "Docker"],
    features: [
      "Reservations & rooms",
      "Clients & services",
      "Payments + receptionist dashboard",
      "Auth & roles (WIP)",
      "Docker + SQL Server container",
    ],
    link: "https://github.com/AnasKrir/H-telLuxe",
  },
  {
    title: "TodoApp — Android (Room + MVVM)",
    category: "Mobile Apps",
    description:
      "Android app in Java with Room, LiveData and RecyclerView for smooth task management.",
    image: "/images/projets/todoapp.jpg",
    icon: "📱",
    tags: ["Java", "Android Studio", "Room", "LiveData", "MVVM"],
    features: [
      "User auth",
      "Tasks CRUD + done state",
      "Local storage (Room/SQLite)",
      "Reactive UI (LiveData)",
    ],
    link: "https://github.com/AnasKrir/TodoApp",
  },
  {
    title: "GStock (Spring Boot) — Agrofourniture",
    category: "Web Apps",
    description:
      "Spring Boot + Thymeleaf stock/clients/orders with roles, Security and cloud deploy.",
    image: "/images/projets/gstock-sb.jpg",
    icon: "📦",
    tags: [
      "Spring Boot 3.5",
      "Thymeleaf",
      "Security 6",
      "JPA",
      "MySQL (dev)",
      "PostgreSQL (prod)",
      "Docker",
    ],
    features: [
      "ADMIN & SELLER roles",
      "Products/Clients/Orders",
      "Auto stock decrement",
      "Simple reporting DTOs",
      "Render + Neon deploy",
    ],
    link: "https://github.com/AnasKrir/gstock",
  },
  {
    title: "DW-Construction — BI Dashboard",
    category: "Data Projects",
    description:
      "Data warehouse + Power BI dashboards (KPI, maps, slicers) with star schema.",
    image: "/images/projets/dw.jpg",
    icon: "📊",
    tags: ["Power BI", "DAX", "Excel ETL", "Star Schema"],
    features: [
      "Centralized construction KPIs",
      "Star schema modeling",
      "Interactive dashboards",
      "PDF/Images/.pbix export",
    ],
    link: "https://github.com/AnasKrir/dw-construction-bi",
  },
  {
    title: "Tennis Championship — C++ Console",
    category: "Console Apps",
    description:
      "Console app to register players, generate matches, track scores and final ranking.",
    image: "/images/projets/tennis.jpg",
    icon: "🎾",
    tags: ["C++17", "CLI", "g++/clang++"],
    features: ["Players management", "Random match draw", "Ranking calculation", "Clear CLI"],
    link: "https://github.com/AnasKrir/tennis-championship-cpp",
  },

  {
  title: "Anime Recommender — Recommendation System",
  category: "Data & AI",
  description:
    "Machine learning recommendation system that predicts anime ratings and generates personalized Top-N recommendations using KNN and SVD.",
  image: "/images/projets/anime-recommender.jpg",
  icon: "🎌",
  tags: ["Python", "Pandas", "Scikit-learn", "Surprise", "Jupyter"],
  features: [
    "KDD-based data processing pipeline",
    "User rating prediction",
    "KNN item-item recommendation",
    "SVD matrix factorization",
    "RMSE / MAE evaluation",
    "Precision@10 & Recall@10 metrics",
    "Personalized Top-N recommendations",
  ],
  link: "https://github.com/AnasKrir/anime-recommender",
},

{
  title: "CineScout — Movie Discovery App",
  category: "Mobile Apps",
  description:
    "Flutter mobile application for discovering movies, searching titles, viewing detailed information, and managing an offline watchlist.",
  image: "/images/projets/cinescout.jpg",
  icon: "🎬",
  tags: ["Flutter", "Dart", "BLoC", "TMDB API", "SQLite"],
  features: [
    "User authentication & session management",
    "Popular & trending movie discovery",
    "Paginated movie search",
    "Detailed movie information & cast",
    "Persistent offline watchlist",
    "TMDB API integration",
    "Light / dark theme",
    "French / English localization",
    "Clean Architecture with BLoC",
  ],
  link: "https://github.com/AnasKrir/CineScout",
},

{
  title: "RestTemplate — Employee Management",
  category: "Web Apps",
  description:
    "Spring Boot REST application with a JSP frontend for managing employees through CRUD operations, pagination, and sorting.",
  image: "/images/projets/resttemplate.jpg",
  icon: "☕",
  tags: ["Java", "Spring Boot", "JPA", "REST API", "JSP", "H2"],
  features: [
    "Employee CRUD operations",
    "REST API with Spring Web",
    "JSP frontend with JSTL",
    "RestTemplate API consumption",
    "H2 in-memory database",
    "Pagination & sorting",
    "Spring Data JPA integration",
    "Separated frontend / backend architecture",
  ],
  link: "https://github.com/AnasKrir/TP6-2-RestTemplate",
},

{
  title: "Event Platform MS — Microservices Platform",
  category: "Web Apps",
  description:
    "Event management and ticketing platform built with Spring Cloud microservices and a React frontend, featuring service discovery, API Gateway, reservations, payments, and notifications.",
  image: "/images/projets/event-platform-ms.jpg",
  icon: "🎟️",
  tags: [
    "Java",
    "Spring Boot",
    "Spring Cloud",
    "React",
    "MySQL",
    "Docker",
    "Eureka",
  ],
  features: [
    "Microservices-based architecture",
    "Event creation & management",
    "User authentication & roles",
    "Ticket reservations",
    "Payment service",
    "Notification service",
    "API Gateway with centralized routing",
    "Eureka service discovery",
    "Spring Cloud Config",
    "React frontend",
  ],
  link: "https://github.com/AnasKrir/event-platform-ms",
},

{
  title: "PFA — Intelligent RAG Assistant",
  category: "Data & AI",
  description:
    "AI-powered administrative assistant for engineering schools using RAG and LLMs to answer questions from PDF documents with role-based access and document generation.",
  image: "/images/projets/pfa-rag-assistant.jpg",
  icon: "🤖",
  tags: [
    "Python",
    "FastAPI",
    "RAG",
    "LLM",
    "Sentence Transformers",
    "SQLite",
    "Jinja2",
  ],
  features: [
    "PDF document ingestion & chunking",
    "Semantic search with embeddings",
    "RAG-based question answering",
    "LLM integration with llama.cpp",
    "Role-based access: Student / Teacher / Admin",
    "Administrative request workflow",
    "Admin dashboard & analytics",
    "Certificate generation",
    "PDF export with ReportLab",
    "Session-based authentication",
  ],
  link: "https://github.com/AnasKrir/pfa-rag-assistant",
},

{
  title: "GTSRB Traffic Signs — Sign Classification & Detection",
  category: "Data & AI",
  description:
    "Deep learning computer vision project for classifying 43 traffic sign categories and detecting signs in road videos using CNNs, ResNet18, PyTorch, and OpenCV.",
  image: "/images/projets/gtsrb-traffic-signs.jpg",
  icon: "🚦",
  tags: [
    "Python",
    "PyTorch",
    "ResNet18",
    "OpenCV",
    "Computer Vision",
    "Jupyter",
  ],
  features: [
    "Classification of 43 traffic sign categories",
    "Custom CNN baseline trained from scratch",
    "ResNet18 transfer learning",
    "Image preprocessing & data augmentation",
    "Accuracy, Precision, Recall & F1 evaluation",
    "43×43 confusion matrix analysis",
    "OpenCV video processing pipeline",
    "Real-time traffic sign inference",
    "Confidence-based detection filtering",
    "Jupyter notebooks & scientific report",
  ],
  link: "https://github.com/AnasKrir/gtsrb-traffic-signs",
},

{
  title: "StartUp Connect AI — Intelligent Startup Scouting",
  category: "Data & AI",
  description:
    "AI-powered web platform for discovering and matching Moroccan startups with business needs using conversational search, hybrid matching, explainable scoring, data enrichment, and analytics.",
  image: "/images/projets/startup-connect-ai.jpg",
  icon: "🚀",
  tags: [
    "Next.js",
    "TypeScript",
    "Python",
    "FastAPI",
    "PostgreSQL",
    "pgvector",
    "OpenAI",
    "Docker",
    "Azure",
  ],
  features: [
    "Conversational AI startup search",
    "Hybrid SQL + vector matching",
    "Multi-criteria DXC scoring",
    "Explainable startup recommendations",
    "Startup catalog with advanced filters",
    "Shortlists & shareable results",
    "Automated startup scraping",
    "Data enrichment & deduplication",
    "User feedback loop",
    "Analytics & data quality dashboard",
    "RBAC & audit logs",
    "PostgreSQL + pgvector",
    "Dockerized deployment",
    "Azure cloud deployment",
  ],
  link: "https://github.com/AnasKrir/startup-connect-ai-v1",
},

];
